{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.exifinterface",
    "module": "exifinterface",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6868708"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "exifinterface-1.3.1.aar",
          "url": "exifinterface-1.3.1.aar",
          "size": 61173,
          "sha512": "1d6236c9304d99d8eefe531f92204fcabe4dde71efd7a6c15aa290f249bb40e5ebceeaf8352327b34289e244f4e25372cf13ceac1c7870f066ab31232fd82104",
          "sha256": "ef168daa6eb744c8395c22b49afa5235e6099868a0377175b6d5e3cdff8d7ffc",
          "sha1": "98add120384f259c9df47ccbb7345b41d246b9d2",
          "md5": "43d0ef6fee4a6a0212b39ab82d6da85f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "exifinterface-1.3.1.aar",
          "url": "exifinterface-1.3.1.aar",
          "size": 61173,
          "sha512": "1d6236c9304d99d8eefe531f92204fcabe4dde71efd7a6c15aa290f249bb40e5ebceeaf8352327b34289e244f4e25372cf13ceac1c7870f066ab31232fd82104",
          "sha256": "ef168daa6eb744c8395c22b49afa5235e6099868a0377175b6d5e3cdff8d7ffc",
          "sha1": "98add120384f259c9df47ccbb7345b41d246b9d2",
          "md5": "43d0ef6fee4a6a0212b39ab82d6da85f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exifinterface-1.3.1-sources.jar",
          "url": "exifinterface-1.3.1-sources.jar",
          "size": 61861,
          "sha512": "e75c3bcca9aa5bfbcdc07fc9307136742588a680d91396b04d39e8018ad907ac3e35003e80ed69efe18ddee40dbfd63f267ba84f8349863d9c2290c2234c5c27",
          "sha256": "47c0b19a5d4a72b86fd2b20cb04d1472f1f7c288b87f3b891360403dd11e2f4a",
          "sha1": "3bf62c462953e9ab78280797fb90fdb5fc9f9289",
          "md5": "b0d2d0be24f98f896e4d014a64ed03e7"
        }
      ]
    }
  ]
}
