{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.flipper",
    "module": "flipper",
    "version": "0.99.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "flipper-0.99.0.aar",
          "url": "flipper-0.99.0.aar",
          "size": 9419986,
          "sha512": "f819337172147bf350519cb12e319d2c04db894ad524757c418a328e65e12c46fefad88c2cb72d58bf7108ad5b2edc23478c772f80f2246ed4ff3fe343a7676f",
          "sha256": "4f018faf46f208b3b1e05d00b5d9d4b13eda0ad98c8dddc11653dd59b3830406",
          "sha1": "143a1d05a15973f778323bf8f0d77dac4413dd38",
          "md5": "e917bf2aa3fbf372a92a47ba138aa8af"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flipper-0.99.0.aar",
          "url": "flipper-0.99.0.aar",
          "size": 9419986,
          "sha512": "f819337172147bf350519cb12e319d2c04db894ad524757c418a328e65e12c46fefad88c2cb72d58bf7108ad5b2edc23478c772f80f2246ed4ff3fe343a7676f",
          "sha256": "4f018faf46f208b3b1e05d00b5d9d4b13eda0ad98c8dddc11653dd59b3830406",
          "sha1": "143a1d05a15973f778323bf8f0d77dac4413dd38",
          "md5": "e917bf2aa3fbf372a92a47ba138aa8af"
        }
      ]
    }
  ]
}
